server:
  port: 9000
  servlet:
    context-path: /questionnaire

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/csust?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: j1927881
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml